[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18.0"
wasm-bindgen = "0.2.100"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-net = "0.6"
gloo-storage = "0.3"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
js-sys = "0.3"
stylist = "0.13"
serde-wasm-bindgen = "0.6.5"
gloo = "0.11"
chrono = "0.4.42"
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "1.0", features = ["v4", "js"] }
reqwest = { version = "0.12", features = ["json"] }
shared = {path = "../shared"}