[workspace]
members = ["backend", "frontend", "shared"]
resolver = "2"

# Fast dev builds
[profile.dev]
opt-level = 1
debug = true
incremental = true

# Optimize deps, not your code
[profile.dev.package."*"]
opt-level = 3
debug = false
